### ISSUE TITLE
ACS712 & ESP32

### ISSUE THREAD

**Issue by lucayuki1635** [alisonsalmeida/emonlib-micropython#1]
Boa tarde,  eu estou tentando usar essa biblioteca com: ESP32 e o medidor de corrente ACS712, porém não está funcionando direito, pois não sei qual pino devo usar como _inPinV, o _inPinI eu consigo seta-lo como 36, porém não existe um para voltage. Já tentei setar o _inPinV como 36 também, porém ele para em um loop na função: calc_voltage_current

OBS: Eu usei a Emonlib na IDE do arduino e funciona sem eu setar o _inPinV. O código/função que usei/preciso é:

EnergyMonitor emon1;
emon1.calcVI();

Que aparentemente no seu código é a função: calc_voltage_current que pede o  _inPinV.

**Comment by alisonsalmeida** [comment]
Boa tarde, o ACS7'2 é um sensor de corrente, voce nao precisa usar calc_voltage_current e sim calc_current_rms, pois voce precisa medir a corrente, entao nao precisa inicializar o pino de tensão.

**Comment by lucayuki1635** [comment]
> Boa tarde, o ACS7'2 é um sensor de corrente, voce nao precisa usar calc_voltage_current e sim calc_current_rms, pois voce precisa medir a corrente, entao nao precisa inicializar o pino de tensão.

Então eu inicializei o calc_current_rms, porém ele envia sempre o mesmo valor. Será que é o numero de samples que devo passar deve ser algo em específico? Pq eu testei com alguns números tipo o 100, porém ele sempre retorna o mesmo valor (9.426277) com algo ligado e sem nd ligado.

**Comment by alisonsalmeida** [comment]
Boa noite, entao, as caracteristicas desse sensor (ACS712) diferem bastante do SCT1307, para qual a lib foi projetada. Além do mais voce precisa usar corrente AC.
